# Generated by Django 3.2.9 on 2021-11-21 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.IntegerField(db_column='Customer_id', primary_key=True, serialize=False)),
                ('customer_gender', models.CharField(blank=True, db_column='Customer_Gender', max_length=15, null=True)),
                ('customer_income_group', models.CharField(blank=True, db_column='Customer_Income_group', max_length=15, null=True)),
                ('customer_region', models.CharField(blank=True, db_column='Customer_Region', max_length=15, null=True)),
                ('customer_marital_status', models.IntegerField(blank=True, db_column='Customer_Marital_status', null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='PolicyDetails',
            fields=[
                ('policy_id', models.IntegerField(db_column='Policy_ID', primary_key=True, serialize=False)),
                ('date_of_purchase', models.CharField(blank=True, db_column='Date_of_Purchase', max_length=20, null=True)),
                ('fuel', models.CharField(blank=True, db_column='Fuel', max_length=15, null=True)),
                ('vehicle_segment', models.CharField(blank=True, db_column='VEHICLE_SEGMENT', max_length=4, null=True)),
                ('premium', models.IntegerField(blank=True, db_column='Premium', null=True)),
                ('bodily_injury_liability', models.IntegerField(blank=True, null=True)),
                ('personal_injury_protection', models.IntegerField(blank=True, null=True)),
                ('property_damage_liability', models.IntegerField(blank=True, null=True)),
                ('collision', models.IntegerField(blank=True, null=True)),
                ('comprehensive', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, db_column='Customer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.customers')),
            ],
            options={
                'db_table': 'policy_details',
            },
        ),
    ]
